name: Facebook Live Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Run Stream
        run: bash stream.sh
